version: '3'
services:
  postgres:
    container_name: postgres-guidecx
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./datapg:/data/db
      - ./docker-files/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  api:
    container_name: backend-api-guidecx
    image: node:14
    working_dir: /usr/src/backend-api-guidecx
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    env_file: .env
    volumes:
      - ./dist/:/usr/src/backend-api-guidecx/dist/
      - ./package.json:/usr/src/backend-api-guidecx/package.json
      - ./ormconfig.json:/usr/src/backend-api-guidecx/ormconfig.json
    ports:
      - '${PORT}:${PORT}'
      - 9229:9229
    links:
      - postgres
